#!/bin/bash

# 查找文件
# find . -name "binderfs.h"
# 查找文件里面的内容
# grep -r "xt_qtaguid.c" .
# 修网络：echo 1 > /proc/sys/net/ipv4/ip_forward
# 修网络：echo 1 > /proc/sys/net/ipv6/ip_forward

ARCH=arm64
DEFCONFIG=vendor/cezanne_user_defconfig

# 你所有 missing 的配置
missing_list=(
"CONFIG_IPC_NS"
"CONFIG_CGROUP_DEVICE"
"CONFIG_IP6_NF_TARGET_MASQUERADE"
"CONFIG_NETFILTER_XT_MATCH_ADDRTYPE"
"CONFIG_NETFILTER_XT_MATCH_IPVS"
"CONFIG_IP6_NF_NAT"
"CONFIG_POSIX_MQUEUE"
"CONFIG_USER_NS"
"CONFIG_CGROUP_PIDS"
"CONFIG_CFQ_GROUP_IOSCHED"
"CONFIG_BLK_CGROUP"
"CONFIG_BLK_DEV_THROTTLING"
"CONFIG_CGROUP_PERF"
"CONFIG_CGROUP_HUGETLB"
"CONFIG_HUGETLB_PAGE"
"CONFIG_HUGETLBFS"
"CONFIG_HUGETLB"
"CONFIG_NET_CLS_CGROUP"
"CONFIG_CGROUP_NET_CLASSID"
"CONFIG_NETFILTER_XT_MATCH_CGROUP"
"CONFIG_CGROUP_NET_PRIO"
"CONFIG_CGROUP_PERF"
"CONFIG_CGROUP_PIDS"
"CONFIG_CGROUP_RDMA"
"CONFIG_CGROUP_WRITEBACK"
"CONFIG_NET_CLS_CGROUP"
"CONFIG_NETFILTER_XT_MATCH_CGROUP"
"CONFIG_CGROUP_NET_PRIO"
"CONFIG_CFS_BANDWIDTH"
"CONFIG_IP_SCTP"
"CONFIG_IP_VS"
"CONFIG_IP_VS_NFCT"
"CONFIG_IP_VS_PROTO_TCP"
"CONFIG_IP_VS_PROTO_UDP"
"CONFIG_IP_VS_RR"
"CONFIG_SECURITY_APPARMOR"
"CONFIG_NFT_CT"
"CONFIG_NF_TABLES"
"CONFIG_NF_TABLES_IPV4"
"CONFIG_NF_TABLES_IPV6"
"CONFIG_NFT_FIB_IPV4"
"CONFIG_NFT_FIB_IPV6"
"CONFIG_NFT_FIB"
"CONFIG_NFT_FIB_INET"
"CONFIG_NFT_FIB_NETDEV"
"CONFIG_NFT_MASQ"
"CONFIG_NFT_NAT"
"CONFIG_NF_TABLES"
"CONFIG_VXLAN"
"CONFIG_BRIDGE_VLAN_FILTERING"
"CONFIG_IPVLAN"
"CONFIG_NET_L3_MASTER_DEV"
"CONFIG_ZPOOL"
"CONFIG_ZSWAP"
"CONFIG_FRONTSWAP"
"CONFIG_ZRAM"
"CONFIG_ZSMALLOC"
"CONFIG_ZSMALLOC_STAT"
"CONFIG_MACVLAN"
"CONFIG_BTRFS_FS"
"CONFIG_BTRFS_FS_POSIX_ACL"
"CONFIG_KPM"
"CONFIG_KVM"
"CONFIG_VIRTUALIZATION"
"CONFIG_HAVE_KVM"
"CONFIG_HAVE_KVM_ARCH_TLB_FLUSH_ALL"
"CONFIG_HAVE_KVM_CPU_RELAX_INTERCEPT"
"CONFIG_HAVE_KVM_EVENTFD"
"CONFIG_HAVE_KVM_INVALID_WAKEUPS"
"CONFIG_HAVE_KVM_IRQCHIP"
"CONFIG_HAVE_KVM_IRQFD"
"CONFIG_HAVE_KVM_IRQ_ROUTING"
"CONFIG_HAVE_KVM_MSI"
"CONFIG_KVM_ARM_HOST"
"CONFIG_KVM_ARM_PMU"
"CONFIG_KVM_ASYNC_PF"
"CONFIG_KVM_ASYNC_PF_SYNC"
"CONFIG_KVM_COMPAT"
"CONFIG_KVM_GENERIC_DIRTYLOG_READ_PROTECT"
"CONFIG_KVM_MMIO"
"CONFIG_KVM_VFIO"
"CONFIG_PTP_1588_CLOCK_KVM"
"CONFIG_PTP_1588_CLOCK"
)

CONFIG_FILE="arch/${ARCH}/configs/${DEFCONFIG}"
for cfg in "${missing_list[@]}"; do
  echo "处理: $cfg = y"

  if grep -q "^$cfg=" "$CONFIG_FILE"; then
    sed -i "s/^$cfg=.*/$cfg=y/" "$CONFIG_FILE"
  else
    echo "$cfg=y" >> "$CONFIG_FILE"
  fi
done

echo "✅ 所有 missing 配置已自动写入：$CONFIG_FILE"
