#!/bin/bash

ARCH=arm64
DEFCONFIG=vendor/cezanne_user_defconfig

# 你所有 missing 的配置
missing_list=(
"CONFIG_SYSCTL"
"CONFIG_NAMESPACES"
"CONFIG_MULTIUSER"
"CONFIG_IPC_NS"
"CONFIG_PID_NS"
"CONFIG_UTS_NS"
"CONFIG_NET_NS"
"CONFIG_NCPFS_NFS_NS"
"CONFIG_NCP_FS"
"CONFIG_IPX"
"CONFIG_OVERLAY_FS"
"CONFIG_IPC_NS"
"CONFIG_CGROUP_DEVICE"
"CONFIG_IP6_NF_TARGET_MASQUERADE"
"CONFIG_NETFILTER_XT_MATCH_ADDRTYPE"
"CONFIG_NETFILTER_XT_MATCH_IPVS"
"CONFIG_IP6_NF_NAT"
"CONFIG_POSIX_MQUEUE"
"CONFIG_CFQ_GROUP_IOSCHED"
"CONFIG_BLK_CGROUP"
"CONFIG_BLK_DEV_THROTTLING"
"CONFIG_CGROUP_PERF"
"CONFIG_CGROUP_HUGETLB"
"CONFIG_HUGETLB_PAGE"
"CONFIG_HUGETLBFS"
"CONFIG_NET_CLS_CGROUP"
"CONFIG_NETFILTER_XT_MATCH_CGROUP"
"CONFIG_CGROUP_NET_PRIO"
"CONFIG_CGROUP_PERF"
"CONFIG_CGROUP_PIDS"
"CONFIG_CGROUP_RDMA"
"CONFIG_CGROUP_WRITEBACK"
"CONFIG_DEVTMPFS"
"CONFIG_DEVTMPFS_MOUNT"
"CONFIG_CFS_BANDWIDTH"
"CONFIG_IP_SCTP"
"CONFIG_IP_VS"
"CONFIG_IP_VS_NFCT"
"CONFIG_IP_VS_PROTO_TCP"
"CONFIG_IP_VS_PROTO_UDP"
"CONFIG_IP_VS_RR"
"CONFIG_SECURITY_APPARMOR"
"CONFIG_NFT_CT"
"CONFIG_NF_TABLES"
"CONFIG_NF_TABLES_IPV4"
"CONFIG_NF_TABLES_IPV6"
"CONFIG_NFT_FIB_IPV4"
"CONFIG_NFT_FIB_IPV6"
"CONFIG_NFT_FIB"
"CONFIG_NFT_MASQ"
"CONFIG_NFT_NAT"
"CONFIG_NF_TABLES"
"CONFIG_VXLAN"
"CONFIG_BRIDGE_VLAN_FILTERING"
"CONFIG_IPVLAN"
"CONFIG_NET_L3_MASTER_DEV"
"CONFIG_MACVLAN"
"CONFIG_BTRFS_FS"
"CONFIG_BTRFS_FS_POSIX_ACL"
"CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE"
"CONFIG_USER_NS_SYSCTL"
"CONFIG_SCHED_WALT"
"CONFIG_SCHED_AUTOGROUP"
"CONFIG_SLUB_MEMCG_SYSFS_ON"
"CONFIG_DEBUG_BLK_CGROUP"
# 外加
"CONFIG_USER_NS"
"CONFIG_UCLAMP_TASK"
"CONFIG_UCLAMP_TASK_GROUP"
"CONFIG_CPU_FREQ_GOV_SCHEDUTIL"
"COMFIG_DEVFREQ_GOV_USERSPACE"
"CONDIF_REGULATOR_USERSPACE_CONSUMER"
"CONFIG_THERMAL_DEFAULT_GOV_USER_SPACE"
)

enable_list=(
"CONFIG_ANDROID_PARANOID_NETWORK"
)

CONFIG_FILE="arch/${ARCH}/configs/${DEFCONFIG}"

echo "========================   open configs   ==========================="

for cfg in "${missing_list[@]}"; do
  echo "处理: $cfg = y"

  if grep -q "^$cfg=" "$CONFIG_FILE"; then
    sed -i "s/^$cfg=.*/$cfg=y/" "$CONFIG_FILE"
  else
    echo "$cfg=y" >> "$CONFIG_FILE"
  fi
done

echo "========================   close configs   ==========================="

for cfg in "${enable_list[@]}"; do
  echo "处理: $cfg = n"

  if grep -q "^$cfg=" "$CONFIG_FILE"; then
    sed -i "s/^$cfg=.*/$cfg=n/" "$CONFIG_FILE"
  else
    echo "$cfg=n" >> "$CONFIG_FILE"
  fi
done

echo "✅ 所有 missing 配置已自动写入：$CONFIG_FILE"