name: Build Kernel
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: read

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
          chmod +x $GITHUB_WORKSPACE/configenv.sh
          bash $GITHUB_WORKSPACE/configenv.sh
    - name: Remove unused packages(移除无用的包)
      if: env.REMOVE_UNUSED_PACKAGES == 'true'
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    # - name: Set swap to 10G
    #   uses: pierotofy/set-swap-space@master
    #   with:
    #     swap-size-gb: 10
        
    - name: Setup ccache
      if: env.ENABLE_CCACHE == 'true'
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
        max-size: 2G
        
    - name: Setup build kernel environment(构建编译内核环境)
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
    
    - name: 切换python(python/python2/python3)
      if: env.SWITCH_PYTHON != ''
      run: |
        if [ ${{ env.SWITCH_PYTHON }} = true ]; then
            sudo rm /usr/bin/python
            sudo ln -s /usr//bin/python3 /usr/bin/python
        fi
        if [ ${{ env.SWITCH_PYTHON }} = false ]; then
            sudo rm /bin/python
            sudo ln -s /bin/python2 /bin/python
        fi
        export PYTHON=/usr/bin/python
        python --version
        python2 --version
        python3 --version
        
    - name: 缓存内核源码与工具链
      uses: actions/cache@v3
      with:
        path: |
            ${{ github.workspace }}/kernel_workspace/android-kernel
            ${{ github.workspace }}/kernel_workspace/${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }}
            ${{ github.workspace }}/kernel_workspace/${{ env.GCC_AND_CLANG_DIR }}
            ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_CLANG_DIR }}
            ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_GCC_64_DIR }}
            ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_GCC_32_DIR }}
            ${{ github.workspace }}/kernel_workspace/tools
            ${{ github.workspace }}/kernel_workspace/boot-source.img
        key: build-cache-${{ env.CACHE_VERSION }}-${{ env.ARCH }}-${{ env.KERNEL_VERSION }}-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_SOURCE_BRANCH }}-${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }}-${{ env.GCC_AND_CLANG_BRANCH }}-${{ env.CUSTOM_CLANG_BRANCH }}-${{ env.CUSTOM_GCC_64_BRANCH }}-${{ env.CUSTOM_GCC_32_BRANCH }}-${{ env.CUSTOM_ANYKERNEL3_BRANCH }}
        restore-keys: |
            ${{ env.CACHE_VERSION }}-${{ env.ARCH }}-${{ env.KERNEL_VERSION }}-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_SOURCE_BRANCH }}-${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }}-${{ env.GCC_AND_CLANG_BRANCH }}-${{ env.CUSTOM_CLANG_BRANCH }}-${{ env.CUSTOM_GCC_64_BRANCH }}-${{ env.CUSTOM_GCC_32_BRANCH }}-${{ env.CUSTOM_ANYKERNEL3_BRANCH }}
        
    - name: Download Custom-Clang(下载Custom-Clang编译器)
      if: env.USE_CUSTOM_CLANG != 'false' || env.USE_GCC_AND_CLANG != 'false'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace

        if [[ "${{ env.USE_GCC_AND_CLANG }}" = "true" && "${{ env.USE_CUSTOM_CLANG }}" != "true" ]]; then
            if [ ! -d ${{ env.GCC_AND_CLANG_DIR }} ]; then
                echo "📥 ${{ env.GCC_AND_CLANG_BRANCH }} 目录不存在，开始下载克隆..."
                git clone --recursive ${{ env.GCC_AND_CLANG_SOURCE }} -b ${{ env.GCC_AND_CLANG_BRANCH }} ${{ env.GCC_AND_CLANG_DIR }} --depth=1
            else
                echo "✅ ${{ env.GCC_AND_CLANG_DIR }} 目录已存在（缓存恢复），跳过下载！开始同步！"
                cd ${{ env.GCC_AND_CLANG_DIR }} && git pull
                cd ..
            fi
        fi
        
        if [[ "${{ env.USE_GCC_AND_CLANG }}" != "true" && "${{ env.USE_CUSTOM_CLANG }}" == "true" ]]; then
            if [ ! -d ${{ env.CUSTOM_CLANG_DIR }} ]; then
                echo "📥 ${{ env.CUSTOM_CLANG_DIR }} 目录不存在，开始下载克隆..."
                if [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.tar.gz' ]]; then
                    wget -O clang.tar.gz ${{ env.CUSTOM_CLANG_SOURCE }}
                    mkdir ${{ env.CUSTOM_CLANG_DIR }}
                    tar -C ${{ env.CUSTOM_CLANG_DIR }}/ -zxvf clang.tar.gz
                elif [[ ${{ env.CUSTOM_CLANG_SOURCE }} =~ git ]]; then
                    git clone ${{ env.CUSTOM_CLANG_SOURCE }} -b ${{ env.CUSTOM_CLANG_BRANCH }} ${{ env.CUSTOM_CLANG_DIR }} --depth=1
                    cd ${{ env.CUSTOM_CLANG_DIR }} && git pull
                    cd ..
                elif [[ ${{ env.CUSTOM_CLANG_SOURCE }} == *'.zip' ]]; then
                    wget -O clang.zip ${{ env.CUSTOM_CLANG_SOURCE }}
                    mkdir ${{ env.CUSTOM_CLANG_DIR }}
                    unzip clang.zip -d ${{ env.CUSTOM_CLANG_DIR }}/
                else
                    echo "请确认clang工具链的文件格式！！！" && exit 1
                fi
            else
                echo "✅ ${{ env.CUSTOM_CLANG_DIR }} 目录已存在（缓存恢复），跳过下载！"
            fi
        fi
        
    - name: Download Custom-Gcc
      if: env.USE_CUSTOM_GCC_64 == 'true' || env.USE_CUSTOM_GCC_32 == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        if [ "${{ env.USE_CUSTOM_GCC_64 }}" = "true" ]; then
            if [ ! -d ${{ env.CUSTOM_GCC_64_DIR }} ]; then
                echo "📥 ${{ env.CUSTOM_GCC_64_DIR }} 目录不存在，开始下载克隆..."
                if [[ ${{ env.CUSTOM_GCC_64_SOURCE }} == *'.tar.gz' ]]; then
                    wget -O gcc-64.tar.gz ${{ env.CUSTOM_GCC_64_SOURCE }}
                    mkdir ${{ env.CUSTOM_GCC_64_DIR }}
                    tar -C ${{ env.CUSTOM_GCC_64_DIR }}/ -zxvf gcc-64.tar.gz
                elif [[ ${{ env.CUSTOM_GCC_64_SOURCE }} =~ git ]]; then
                    git clone ${{ env.CUSTOM_GCC_64_SOURCE }} -b ${{ env.CUSTOM_GCC_64_BRANCH }} ${{ env.CUSTOM_GCC_64_DIR }} --depth=1
                    cd ${{ env.CUSTOM_GCC_64_DIR }} && git pull
                    cd ..
                elif [[ ${{ env.CUSTOM_GCC_64_SOURCE }} == *'.zip' ]]; then
                    wget -O gcc-64.zip ${{ env.CUSTOM_GCC_64_SOURCE }}
                    mkdir ${{ env.CUSTOM_GCC_64_DIR }}
                    unzip gcc-64.zip -d ${{ env.CUSTOM_GCC_64_DIR }}/
                else
                    echo "请确认GCC工具链的文件格式！！！" && exit 1
                fi
            else
                echo "✅ ${{ env.CUSTOM_GCC_64_DIR }} 目录已存在（缓存恢复），跳过下载！"
            fi
            echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/kernel_workspace/${{ env.CUSTOM_GCC_64_DIR }}/bin/${{ env.CUSTOM_GCC_64_BIN }}" >> $GITHUB_ENV || echo "⚠️ 写入 gcc-64 失败"
        fi
        if [ "${{ env.USE_CUSTOM_GCC_32 }}" = "true" ]; then
            if [ ! -d ${{ env.CUSTOM_GCC_32_DIR }} ]; then
                echo "📥 ${{ env.CUSTOM_GCC_32_DIR }} 目录不存在，开始下载克隆..."
                if [[ ${{ env.CUSTOM_GCC_32_SOURCE }} == *'.tar.gz' ]]; then
                    wget -O gcc-32.tar.gz ${{ env.CUSTOM_GCC_32_SOURCE }}
                    mkdir ${{ env.CUSTOM_GCC_32_DIR }}
                    tar -C ${{ env.CUSTOM_GCC_32_DIR }}/ -zxvf gcc-32.tar.gz
                elif [[ ${{ env.CUSTOM_GCC_32_SOURCE }} =~ git ]]; then
                    git clone ${{ env.CUSTOM_GCC_32_SOURCE }} -b ${{ env.CUSTOM_GCC_32_BRANCH }} ${{ env.CUSTOM_GCC_32_DIR }} --depth=1
                elif [[ ${{ env.CUSTOM_GCC_32_SOURCE }} == *'.zip' ]]; then
                    wget -O gcc-32.zip ${{ env.CUSTOM_GCC_32_SOURCE }}
                    mkdir ${{ env.CUSTOM_GCC_32_DIR }}
                    unzip gcc-32.zip -d ${{ env.CUSTOM_GCC_32_DIR }}/
                else
                    echo "请确认GCC工具链的文件格式！！！" && exit 1
                fi
            else
                echo "✅ ${{ env.CUSTOM_GCC_32_DIR }} 目录已存在（缓存恢复），跳过下载！"
            fi
            echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/kernel_workspace/${{ env.CUSTOM_GCC_32_DIR }}/bin/${{ env.CUSTOM_GCC_32_BIN }}" >> $GITHUB_ENV || echo "⚠️ 写入 gcc-32 失败"
        fi
        
        
    - name: Download kernel source(下载内核源码以及驱动模块)
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        
        if [ ! -d "android-kernel" ]; then
            echo "📥 android-kernel 目录不存在，开始下载克隆..."
            git clone --recursive ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
            cd android-kernel
            cd ..
        else
            echo "✅ android-kernel 目录已存在（缓存恢复），跳过下载！开始同步！"
            cd android-kernel && git pull
            cd ..
        fi
        if [ "${{ env.USE_MTK_KERNEL_MODULES }}" = "true" ]; then
            if [ ! -d ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} ]; then
                echo "📥 ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} 目录不存在，开始下载克隆..."
                git clone --recursive ${{ env.MTK_KERNEL_MODULES_SOURCE }} -b ${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }} ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} --depth=1
            else
                echo "✅ ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} 目录已存在（缓存恢复），跳过下载！开始同步！"
                cd ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} && git pull
                cd ..
            fi
        fi
        if [ "${{ env.ADD_LOCALVERSION_TO_FILENAME }}" = "true" ]; then
            echo "LOCALVERSION=$(cat localversion)" >> $GITHUB_ENV || echo "⚠️ 写入 LOCALVERSION 失败"
        else
            echo "LOCALVERSION=" >> $GITHUB_ENV || echo "⚠️ 写入 LOCALVERSION 失败"
        fi
        
    - name: Download mkbootimg tools(下载mkbootimg解包工具)
      if: env.BUILD_BOOT_IMG == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        if [ ! -d "tools" ]; then
            echo "📥 tools 目录不存在，开始下载克隆..."
            git clone https://android.googlesource.com/platform/system/tools/mkbootimg tools -b master-kernel-build-2022 --depth=1
        else
            echo "✅ tools 目录已存在（缓存恢复），跳过下载！"
        fi
        
    - name: Setup KernelSU(开启KSU)
      if: env.ENABLE_KERNELSU == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.KERNELSU_TAG }}
        KSU_VERSION=$(cd KernelSU && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
        echo "UPLOADNAME=-KernelSU_$KSU_VERSION" >> $GITHUB_ENV || echo "⚠️ 写入 UPLOADNAME 失败"
        echo "✅ kernelsu 的 setup.sh 下载完成"
        
    - name: Setup Configuration for Kernel(开启内核选项)
      run: |
        echo "当前目录：$(pwd)"
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel

        if [ "${{ env.USE_SETUP_KERNEL_CONFIG }}" = "true" ]; then
            echo "正在设置 kernel-config... "
            rm -f setup_kernel_config.sh
            curl -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" -o setup_kernel_config.sh "${{ env.SETUP_KERNEL_CONFIG_LINK }}"
            chmod +x setup_kernel_config.sh
            ./setup_kernel_config.sh
            echo "✅ kernel-config 设置完成"
        fi
        
    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        
        echo "================================== 调试输出 =================================="
        echo "所有包含 false 的环境变量："
        env | grep true || echo "无 false 变量"
        echo "============================================================================="
        echo "所有包含 true 的环境变量："
        env | grep false || echo "无 true 变量"
        echo "=============================================================================="
        
        if [ ! -z ${{ env.KSU_EXPECTED_SIZE }} ] && [ ! -z ${{ env.KSU_EXPECTED_HASH }} ]; then
          export KSU_EXPECTED_SIZE=${{ env.KSU_EXPECTED_SIZE }}
          export KSU_EXPECTED_HASH=${{ env.KSU_EXPECTED_HASH }}
        fi
        
        if [ "${{ env.USE_MTK_KERNEL_MODULES }}" = "true" ] || [ "${{ env.USE_BUILD_BASH }}" = "true" ]; then
            rm -f build.sh
            curl -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" -o build.sh "${{ env.BUILD_BASH_LINK }}"
            chmod +x build.sh
            ./build.sh
        else
            rm -rf out/
            make mrproper 2>/dev/null || true
            echo "================================================================================"
            echo "CUSTOM_CMDS = '${{ env.CUSTOM_CMDS }}'"
            echo "EXTRA_CMDS  = '${{ env.EXTRA_CMDS }}'"
            export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
            export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/lib64:$LD_LIBRARY_PATH
            export KBUILD_BUILD_HOST=Github-Action
            export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
            echo "KBUILD_BUILD_USER=$KBUILD_BUILD_USER"
            echo "KBUILD_BUILD_HOST=$KBUILD_BUILD_HOST"
            echo "================================================================================"

            if [ ${{ env.METHOD_OK }} = 'A' ]; then
                make -j$(nproc --all) CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.KERNEL_CONFIG }}
                if [ ${{ env.ENABLE_CCACHE }} = true ]; then
                    make -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
                else
                    make -j$(nproc --all) CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
                fi
            fi
            if [ ${{ env.METHOD_OK }} = 'B' ]; then
                make -j$(nproc --all) CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} CROSS_COMPILE="aarch64-linux-gnu-" CROSS_COMPILE_ARM32="arm-linux-gnueabi-" ${{ env.KERNEL_CONFIG }}
                if [ ${{ env.ENABLE_CCACHE }} = true ]; then
                    make -j$(nproc --all) CC="ccache clang" O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} CROSS_COMPILE="aarch64-linux-gnu-" CROSS_COMPILE_ARM32="arm-linux-gnueabi-" ${{ env.EXTRA_CMDS }}${{ env.LLVM_PARAMS }}
                else
                    make -j$(nproc --all) CC=clang O=out ARCH=${{ env.ARCH }} ${{ env.CUSTOM_CMDS }} CROSS_COMPILE="aarch64-linux-gnu-" CROSS_COMPILE_ARM32="arm-linux-gnueabi-" ${{ env.EXTRA_CMDS }}${{ env.LLVM_PARAMS }}
                fi
            fi
        fi

    - name: Check a kernel output files(检查编译内核生成文件)
      run: |
       cd $GITHUB_WORKSPACE/kernel_workspace
       if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
       else
           echo "Kernel output file is empty"
       fi

       if [ "${{ env.NEED_DTBO }}" = "true" ]; then
           if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ]; then
               echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
           else
               echo "DTBO image is empty"
           fi
       fi
       
    - name: 压缩 MTK 内核模块
      if: env.CHECK_FILE_IS_OK == 'true' && env.USE_MTK_KERNEL_MODULES == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out
        zip -r modules.zip out_modules/
        echo "✅ modules.zip 压缩完成"
        
    - name: Make Anykernel3(制作Anykernel3卡刷包)
      if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 != 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
        sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
        sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
        cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
        if [ "${{ env.CHECK_DTBO_IS_OK }}" = "true" ]; then
            cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
        fi
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        echo "✅ Anykernel3.zip 制作完成"
        
    - name: Make Custom-Anykernel3(制作Custom_Anykernel3卡刷包)
      if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} =~ git ]]; then
            if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.gz' ]]; then
                wget -O AnyKernel3.tar.gz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
                mkdir AnyKernel3
                tar -C AnyKernel3/ -zxvf AnyKernel3.tar.gz
            else
                git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
            fi
        else
            wget -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
            mkdir AnyKernel3
            unzip AnyKernel3.zip -d AnyKernel3/
        fi
        cp android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
        if [ "${{ env.CHECK_DTBO_IS_OK }}" = "true" ]; then
            cp android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img AnyKernel3/
        fi
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        echo "✅ Anykernel3.zip 制作完成"
        
    - name: Download source boot image(下载直链内核镜像)
      if: env.BUILD_BOOT_IMG == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        if [ -f boot-source.img ]; then
            echo "✅ boot-source.img 文件已存在（缓存恢复），跳过下载！"
            echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
            echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV || echo "⚠️ 设置 HAVE_SOURCE_BOOT_IMAGE 失败"
        else
            echo "📥 boot-source.img 文件不存在，开始下载..."
            wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
            echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
            echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV || echo "⚠️ 设置 HAVE_SOURCE_BOOT_IMAGE 失败"
        fi
        
    - name: Make boot image(制作合成新的内核镜像)
      if: env.HAVE_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        rm -rf out
        mkdir -p out
        tools/unpack_bootimg.py --boot_img boot-source.img --out out/
        cp -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} out/kernel
        tools/mkbootimg.py \
          $(test -f out/header_version && echo "--header_version $(cat out/header_version)") \
          $(test -f out/kernel && echo "--kernel out/kernel") \
          $(test -f out/ramdisk && echo "--ramdisk out/ramdisk") \
          $(test -f out/cmdline && echo "--cmdline $(cat out/cmdline)") \
          $(test -f out/base && echo "--base $(cat out/base)") \
          $(test -f out/pagesize && echo "--pagesize $(cat out/pagesize)") \
          $(test -f out/kernel_offset && echo "--kernel_offset $(cat out/kernel_offset)") \
          $(test -f out/ramdisk_offset && echo "--ramdisk_offset $(cat out/ramdisk_offset)") \
          $(test -f out/tags_offset && echo "--tags_offset $(cat out/tags_offset)") \
          $(test -f out/dtb && echo "--dtb out/dtb") \
          $(test -f out/dtb_offset && echo "--dtb_offset $(cat out/dtb_offset)") \
          $(test -f out/os_version && echo "--os_version $(cat out/os_version)") \
          $(test -f out/os_patch_level && echo "--os_patch_level $(cat out/os_patch_level)") \
          -o boot.img
        ORIGINAL_SIZE=$(stat -c "%s" boot-source.img)
        echo "原 boot 大小: $ORIGINAL_SIZE 字节"
        truncate -s $ORIGINAL_SIZE boot.img
        echo "已填充新 boot.img 到原版大小: $(stat -c "%s" boot.img) 字节"
        if [ -f boot.img ]; then
            echo "MAKE_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
            echo "✅ 新 boot.img 制作完成！大小与原版一致！"
            ls -lh boot.img
        else
            echo "❌ Boot image 制作失败"
        fi
        
    - name: Upload ${{ env.KERNEL_IMAGE_NAME }} (上传)
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_IMAGE_NAME }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }}
        
    - name: Upload ${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }} (上传)
      if: env.MTK_KERNEL_MODULES_UPLOAD == 'true' || env.USE_MTK_KERNEL_MODULES == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }}-${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/android-kernel/out/modules.zip
        
    - name: Upload AnyKernel3(上传Upload AnyKernel3)
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/AnyKernel3/*
        
    - name: Upload DTBO image(上传 DTBO image)
      if: env.CHECK_DTBO_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: dtbo-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img
        
    - name: Upload boot image(上传 boot image)
      if: env.MAKE_BOOT_IMAGE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: boot${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_workspace/boot.img
        
    - name: 强制删除旧缓存
      run: |
        gh cache delete "${{ env.CACHE_VERSION }}-${{ env.ARCH }}-${{ env.KERNEL_VERSION }}-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_SOURCE_BRANCH }}-${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }}-${{ env.GCC_AND_CLANG_BRANCH }}-${{ env.CUSTOM_CLANG_BRANCH }}-${{ env.CUSTOM_GCC_64_BRANCH }}-${{ env.CUSTOM_GCC_32_BRANCH }}-${{ env.CUSTOM_ANYKERNEL3_BRANCH }}" || true
      env:
        GH_TOKEN: ${{ github.token }}
        
    - name: 强制保存缓存
      if: always()  # 关键：无论前面步骤成功/失败，都执行
      uses: actions/cache/save@v3
      with:
        path: |
          ${{ github.workspace }}/kernel_workspace/android-kernel
          ${{ github.workspace }}/kernel_workspace/${{ env.MTK_KERNEL_MODULES_SOURCE_DIR }}
          ${{ github.workspace }}/kernel_workspace/${{ env.GCC_AND_CLANG_DIR }}
          ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_CLANG_DIR }}
          ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_GCC_64_DIR }}
          ${{ github.workspace }}/kernel_workspace/${{ env.CUSTOM_GCC_32_DIR }}
          ${{ github.workspace }}/kernel_workspace/tools
          ${{ github.workspace }}/kernel_workspace/boot-source.img
        key: ${{ env.CACHE_VERSION }}-${{ env.ARCH }}-${{ env.KERNEL_VERSION }}-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_SOURCE_BRANCH }}-${{ env.MTK_KERNEL_MODULES_SOURCE_BRANCH }}-${{ env.GCC_AND_CLANG_BRANCH }}-${{ env.CUSTOM_CLANG_BRANCH }}-${{ env.CUSTOM_GCC_64_BRANCH }}-${{ env.CUSTOM_GCC_32_BRANCH }}-${{ env.CUSTOM_ANYKERNEL3_BRANCH }}
